### PR TITLE
[timeline] fix display of unit above

### LINKED ISSUE #140: [Timeline] Fix display of unit above
Unit above gets displayed in the wrong way, not starting from its beginning (this applies from weeks and above, not for days below => hours / mins).

### PR DESCRIPTION
**Pull request by CrisGrud**
This PR closes #140

### CODE REVIEW

File: src/grid/CellGroup/index.tsx [hunk 1]
```diff
@@ -7,11 +7,11 @@ import { displayAboveInterval } from "../../utils/time-resolution";
 
 interface GridCellGroupProps {
   column: Interval;
-  height: number;
   index: number;
+  dayInfo?: { thisMonth?: number; untilNow?: number; backHour: boolean; forNowHour: boolean }[];
 }
```
Comment (luciob) [inline src/grid/CellGroup/index.tsx:12]: Add a type for this data structure

File: src/grid/Cells/index.tsx [hunk 2]
```diff
@@ -10,12 +11,36 @@ interface GridCellsProps {
...
+        const startDay = getStartMonthsDay(interval.start!);
+        const daysToMonthEnd = currentMonthDays - Number(startDay) + 1;
+        dayInfo.push({ thisMonth: daysToMonthEnd, untilNow: daysToMonthEnd, backHour: bchour, forNowHour: false });
+        return;
+      }
+      const forNowHour = dayInfo[index - 1].forNowHour ? true : dayInfo[index - 1].backHour ? true : false;
+      const n = dayInfo[index - 1].untilNow! + currentMonthDays;
+      dayInfo.push({ thisMonth: currentMonthDays, untilNow: n, backHour: bchour, forNowHour: forNowHour });
+    });
+  }
```
Comment (luciob) [inline src/grid/Cells/index.tsx:38]: Let's use a memo here if possible

**Review by luciob — CHANGES_REQUESTED** [review]

File: src/timeline/TimelineContext.tsx [hunk 3]
```diff
@@ -206,7 +206,25 @@ export const TimelineProvider = ({
...
+    const intervalEnd = interval.end!;
+
+    let blockStart = intervalStart;
+    while (blockStart < intervalEnd) {
+      let blockEnd = blockStart.endOf(unitAbove);
+      if (blockEnd > intervalEnd) {
+        blockEnd = intervalEnd;
+      }
+
+      logError("Adding Block", `${blockStart.toFormat("dd/MM/yy HH:mm")} > ${blockEnd.toFormat("dd/MM/yy HH:mm")}`);
```
Comment (luciob) [inline src/timeline/TimelineContext.tsx]: Remove `logError` call or switch to `logDebug`, or delete

**Review by luciob — APPROVED** [review]
